### PR TITLE
Added basic request handler functionality

### PR DESCRIPTION
**Pull request by AChan118**
[request_handler.py#9](https://github.com/NSS-Day-Cohort-58/rare-python-server-shockwave-blazers/issues/9)

# Description

Added the basic request we will need to start

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

To test this branch:
Git fetch –all
Git checkout AC-Request-Handler

- [x] Test A Postman
	
# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by jvw3 — APPROVED** [review]
looks good!

**Review by shanestanddev — APPROVED** [review]
dat code be lookin good!

**Comment by AChan118** [comment]
Get and post requests need to be looked at again when query strings come into play

**Review by brandonherbison — APPROVED** [review]
sheesh bro!! fire code on God 🔥🐐

**Pull request merged**
